export interface User {
  id: number;
  email: string;
  firstName: string;
  lastName: string;
  roles: string[];
}
  
export type AuditLogResponse = any; export type PageResponse<T> = any; export type LoginRequest = any; export type AuthResponse = any; export type UserProfile = any; export type RefreshTokenRequest = any; export type CollegeRequest = any; export type CollegeResponse = any; export type CollegeSummaryResponse = any; export type CourseRequest = any; export type CourseResponse = any; export type CourseSummaryResponse = any; export type AdminDashboardResponse = any; export type ProfessorDashboardResponse = any; export type StudentDashboardResponse = any; export type DepartmentRequest = any; export type DepartmentResponse = any; export type DepartmentSummaryResponse = any; export type ExaminationRequest = any; export type ExaminationResponse = any; export type ExamSubjectRequest = any; export type ExamSubjectResponse = any; export type FeeStructureRequest = any; export type FeeStructureResponse = any; export type FeeInvoiceRequest = any; export type FeeInvoiceResponse = any; export type PaymentRequest = any; export type PaymentResponse = any; export type StudentFeeSummaryResponse = any; export type SendNotificationRequest = any; export type NotificationResponse = any; export type NotificationPreferenceRequest = any; export type NotificationPreferenceResponse = any; export type ProfessorRequest = any; export type ProfessorResponse = any; export type ProfessorSummaryResponse = any; export type ResultEntryRequest = any; export type ResultResponse = any; export type StudentReportCardResponse = any; export type StudentRequest = any; export type StudentResponse = any; export type StudentSummaryResponse = any; export type EnrollmentRequest = any; export type EnrollmentResponse = any; export type SubjectRequest = any; export type SubjectResponse = any; export type SubjectSummaryResponse = any; export type SubjectAssignmentRequest = any; export type SubjectAssignmentResponse = any;
export type BatchAttendanceRequest = any; export type AttendanceResponse = any; export type AttendanceStatsResponse = any;
